### ISSUE TITLE
Projekt gotowy do oceny

### ISSUE THREAD

**Issue by RedTheFedoraShark** [paradrop-soft/cardboxer#37]

**Comment by JOtworowski** [comment]
Projekt jest dopracowany jednak mam kilka uwag. Tak jak rozmawialiśmy na zajęciach użycie wielu pointerów i plików json częściowo spełnia wymagania zarządzania pamięcią. Poza tym udało mi się znaleźć jednego replikowalnego buga. Mając na ręce karty One.. , ...two... i ...three gra zawiesza się po automatycznym rzuceniu karty ..two.. . W przypadku formatowania kodu i prowadzenia projektu plusem jest uporządkowanie plików w folderach headers, res itd. poza tym kod formatowany jest czytelnie i przemyślanie. Niewielkim mankamentem w tym przypadku są fragmenty wykomentowanego nieużywanego kodu. Jeśli chodzi o warstwę gameplayową to z wyjątek wspomnianego wyżej buga gra działa płynnie, a animacje są dopracowane. Mechanika kart jest z opcjami defence i offence jest moim zdaniem ciekawym i kreatywnym rozwiązaniem. Jedynym problem moim zdaniem jest balans gry. Z uwagi na to że do dyspozycji mamy tylko trzy karty, a dobieranie powoduje utratę ruchu i do tego sprowadza się do recyklingu użytych już kart przy pechowym losowaniu otwierającej ręki porażka zdaje się wynikać z czynników niezależnych od gracza (rng) a nie jego błędów

Moja propozycja oceny to 87,5%, ponieważ mimo opisanych wcześniej uwag projekt ma ciekawy pomysł, wykonany jest starannie i działa niemalże bez problemów.

**Comment by m47eus2** [comment]
Dobrze, dziękujemy
